import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSidebar: [
    "getting-started",
    "configuration",
    "authentication",
    {
      type: "category",
      label: "Exporters",
      items: [
        {
          type: "autogenerated",
          dirName: "exporters",
        },
      ],
    },
    {
      type: "category",
      label: "API Reference",
      items: [
        {
          type: "autogenerated",
          dirName: "api",
        },
      ],
    },
    {
      type: "category",
      label: "Dashboard",
      items: [
        {
          type: "autogenerated",
          dirName: "dashboard",
        },
      ],
    },
    {
      type: "category",
      label: "Plugins",
      items: [
        {
          type: "autogenerated",
          dirName: "plugins",
        },
      ],
    },
  ],
};

export default sidebars;
